---
- name: Install and configure Zabbix Server, Web Frontend, and Agent on Zabbix Server
  hosts: monitoring
  become: yes
  vars_prompt:
    - name: "mysql_root_password"
      prompt: "Enter MySQL root password"
      private: yes

    - name: "mysql_zabbix_password"
      prompt: "Enter MySQL password for Zabbix"
      private: yes

  tasks:
    - name: Gather installed package facts
      package_facts:
        manager: apt

    - name: Install Docker if not already installed
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: "'docker.io' not in ansible_facts.packages"

    - name: Check if Zabbix MySQL container is running
      shell: docker ps --filter "name=zabbix-mysql" --format "{{.Names}}"
      register: zabbix_mysql_container
      changed_when: false

    - name: Start MySQL container if not running
      command: >
        docker run -d --name zabbix-mysql
        -e MYSQL_DATABASE=zabbix
        -e MYSQL_USER=zabbix
        -e MYSQL_PASSWORD={{ mysql_zabbix_password }}
        -e MYSQL_ROOT_PASSWORD={{ mysql_root_password }}
        -v /var/lib/mysql:/var/lib/mysql
        mysql:5.7
      when: zabbix_mysql_container.stdout == ""

    - name: Check if Zabbix Server container is running
      shell: docker ps --filter "name=zabbix-server" --format "{{.Names}}"
      register: zabbix_server_container
      changed_when: false

    - name: Start Zabbix Server container if not running
      command: >
        docker run -d --name zabbix-server
        --link zabbix-mysql:mysql
        -e DB_SERVER_HOST="mysql"
        -e MYSQL_USER="zabbix"
        -e MYSQL_PASSWORD={{ mysql_zabbix_password }}
        -p 10051:10051
        zabbix/zabbix-server-mysql:latest
      when: zabbix_server_container.stdout == ""

    - name: Check if Zabbix Web container is running
      shell: docker ps --filter "name=zabbix-web" --format "{{.Names}}"
      register: zabbix_web_container
      changed_when: false

    - name: Start Zabbix Web interface container if not running
      command: >
        docker run -d --name zabbix-web
        --link zabbix-server:zabbix-server
        --link zabbix-mysql:mysql
        -e DB_SERVER_HOST="mysql"
        -e MYSQL_USER="zabbix"
        -e MYSQL_PASSWORD={{ mysql_zabbix_password }}
        -p 80:8080
        zabbix/zabbix-web-nginx-mysql:latest
      when: zabbix_web_container.stdout == ""

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix Agent to point to local Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=10.10.1.100'
        backup: yes

    - name: Configure Zabbix Agent for active checks to local server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: 'ServerActive=10.10.1.100'
        backup: yes

    - name: Set the hostname for Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: 'Hostname={{ inventory_hostname }}'
        backup: yes

    - name: Enable and start Zabbix Agent service
      systemd:
        name: zabbix-agent
        enabled: yes
        state: started

    - name: Restart Zabbix Agent to apply configuration changes
      service:
        name: zabbix-agent
        state: restarted

- name: Install and configure Zabbix Agent on all other nodes
  hosts: docker_swarm_manager,docker_swarm_workers,elk
  become: yes
  tasks:
    - name: Add Zabbix repository
      apt_repository:
        repo: "deb http://repo.zabbix.com/zabbix/6.0/ubuntu/ $(lsb_release -cs) main"
        state: present
        filename: 'zabbix'

    - name: Add Zabbix public GPG key
      apt_key:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix Agent to point to Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=10.10.1.100'
        backup: yes

    - name: Configure Zabbix Agent for active checks to Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: 'ServerActive=10.10.1.100'
        backup: yes

    - name: Set the hostname for Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: 'Hostname={{ inventory_hostname }}'
        backup: yes

    - name: Enable and start Zabbix Agent service
      systemd:
        name: zabbix-agent
        enabled: yes
        state: started

    - name: Restart Zabbix Agent to apply configuration changes
      service:
        name: zabbix-agent
        state: restarted