---
- name: Deploy Zabbix Server and Web in Docker Containers
  hosts: monitoring
  become: yes
  vars_prompt:
    - name: "mysql_root_password"
      prompt: "Enter MySQL root password"
      private: yes

    - name: "mysql_zabbix_password"
      prompt: "Enter MySQL password for Zabbix"
      private: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Zabbix server image
      command: docker pull zabbix/zabbix-server-mysql:latest

    - name: Pull MySQL image
      command: docker pull mysql:5.7

    - name: Pull Zabbix web interface image
      command: docker pull zabbix/zabbix-web-nginx-mysql:latest

    - name: Start MySQL container
      command: >
        docker run -d --name zabbix-mysql
        -e MYSQL_DATABASE=zabbix
        -e MYSQL_USER=zabbix
        -e MYSQL_PASSWORD={{ mysql_zabbix_password }}
        -e MYSQL_ROOT_PASSWORD={{ mysql_root_password }}
        -v /var/lib/mysql:/var/lib/mysql
        mysql:5.7
      args:
        creates: /var/lib/mysql

    - name: Start Zabbix Server container
      command: >
        docker run -d --name zabbix-server
        --link zabbix-mysql:mysql
        -e DB_SERVER_HOST="mysql"
        -e MYSQL_USER="zabbix"
        -e MYSQL_PASSWORD={{ mysql_zabbix_password }}
        -p 10051:10051
        zabbix/zabbix-server-mysql:latest

    - name: Start Zabbix Web interface container
      command: >
        docker run -d --name zabbix-web
        --link zabbix-server:zabbix-server
        --link zabbix-mysql:mysql
        -e DB_SERVER_HOST="mysql"
        -e MYSQL_USER="zabbix"
        -e MYSQL_PASSWORD={{ mysql_zabbix_password }}
        -p 80:8080
        zabbix/zabbix-web-nginx-mysql:latest

    - name: Ensure Zabbix Server and Web are running
      command: docker ps
