---
- name: Install and configure Zabbix Agent on all nodes
  hosts: docker_swarm_manager,docker_swarm_workers,elk
  become: yes
  tasks:
    - name: Download Zabbix release package
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb"
        dest: "/tmp/zabbix-release_6.0-4+ubuntu22.04_all.deb"

    - name: Install Zabbix release package using dpkg
      shell: dpkg -i /tmp/zabbix-release_6.0-4+ubuntu22.04_all.deb
      args:
        warn: false
      register: dpkg_install
      ignore_errors: true

    - name: Ensure apt cache is updated after package installation
      apt:
        update_cache: yes
      when: dpkg_install.changed

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix Agent to point to Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=10.10.1.100'
        backup: yes

    - name: Configure Zabbix Agent for active checks to Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: 'ServerActive=10.10.1.100'
        backup: yes

    - name: Set the hostname for Zabbix Agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: 'Hostname={{ inventory_hostname }}'
        backup: yes

    - name: Enable and start Zabbix Agent service
      systemd:
        name: zabbix-agent
        enabled: yes
        state: started

    - name: Restart Zabbix Agent to apply configuration changes
      service:
        name: zabbix-agent
        state: restarted
