---
- name: Install and configure Elasticsearch on Docker
  hosts: elastic.internal-cloud
  become: yes
  tasks:
    - name: Check if containerd.io is installed
      shell: dpkg -l | grep containerd.io
      register: containerd_installed
      ignore_errors: true

    - name: Remove containerd.io if installed
      apt:
        name: containerd.io
        state: absent
      when: containerd_installed.rc == 0

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker if not already installed
      apt:
        name: docker.io
        state: present

    - name: Check if Elasticsearch image is already pulled
      command: docker images -q elasticsearch:8.15.1
      register: elasticsearch_image
      ignore_errors: true

    - name: Pull Elasticsearch image if not present
      command: docker pull elasticsearch:8.15.1
      when: elasticsearch_image.stdout == ""

    - name: Ensure Elasticsearch config directory exists
      file:
        path: /opt/elasticsearch/config
        state: directory
        owner: root
        group: root
        mode: '0766'

    - name: Ensure Elasticsearch data directory exists
      file:
        path: /opt/elasticsearch/data
        state: directory
        owner: root
        group: root
        mode: '0777'

    - name: Ensure Elasticsearch log directory exists
      file:
        path: /opt/elasticsearch/log
        state: directory
        owner: root
        group: root
        mode: '0766'

    - name: Render Elasticsearch configuration from template
      template:
        src: /HA-web/ansible-playbooks/templates/ELK/elasticsearch.yml.j2
        dest: /opt/elasticsearch/config/elasticsearch.yml
        owner: root
        group: root
        mode: 0666

    - name: Run Elasticsearch container
      community.docker.docker_container:
        name: elasticsearch
        image: elasticsearch:8.15.1
        state: started
        restart_policy: always
        ports:
          - "9200:9200"
          - "9300:9300"
        # volumes:
        #   - /opt/elasticsearch/data:/usr/share/elasticsearch/data
        #   - /opt/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        #   - /opt/elasticsearch/log:/var/log/elasticsearch