---
- name: Install and configure Elasticsearch on Ubuntu 24.04
  hosts: elastic.internal-cloud
  become: yes
  tasks:

    - name: Add the Elasticsearch GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add the Elastic repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: 'elastic-8.x'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present

    - name: Enable Elasticsearch service
      systemd:
        name: elasticsearch
        enabled: yes
        state: started

    - name: Configure Elasticsearch (optional)
      template:
        src: templates/elasticsearch/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: elasticsearch
        group: elasticsearch
        mode: 0644
      notify:
        - Restart Elasticsearch

  handlers:
    - name: Restart Elasticsearch
      systemd:
        name: elasticsearch
        state: restarted
