---
- name: Install and configure Filebeat in Docker on Swarm nodes
  hosts: docker_swarm_manager, docker_swarm_workers
  become: yes
  tasks:
    - name: Check if Filebeat image is already pulled
      command: docker images -q elastic/filebeat:8.15.1
      register: filebeat_image
      ignore_errors: true

    - name: Pull Filebeat image if not present
      command: docker pull elastic/filebeat:8.15.1
      when: filebeat_image.stdout == ""

    - name: Check if filebeat container is already pulled
      command: docker ps --filter "name=elastic/filebeat"
      register: filebeat_container
      ignore_errors: true

    - name: Remove existing filebeat service if it exists
      command: docker rm elastic/filebeat --force
      when: filebeat_container.stdout != ""
      ignore_errors: true

    - name: Re-check if filebeat service exists after removal
      command: docker ps --filter "name=elastic/filebeat"
      register: filebeat_container
      failed_when: false
      changed_when: false

    - name: Ensure Filebeat config directory exists
      file:
        path: /opt/filebeat/config
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Render Filebeat configuration from template
      template:
        src: /HA-web/ansible-playbooks/templates/ELK/filebeat.yml.j2
        dest: /opt/filebeat/config/filebeat.yml
        owner: root
        group: root
        mode: 0644

    - name: Run Filebeat container
      community.docker.docker_container:
        name: filebeat
        image: elastic/filebeat:8.15.1
        state: started
        restart_policy: always
        volumes:
          - /var/lib/docker/containers:/var/lib/docker/containers:ro
          - /opt/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        command: ["filebeat", "-e", "-strict.perms=false"]