---
- name: Install and configure Kibana
  hosts: kibana.internal-cloud
  become: yes
  tasks:
    - name: Add Elastic APT repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: 'elastic-8.x'

    - name: Install Kibana
      apt:
        name: kibana
        state: present
        update_cache: yes

    - name: Configure Kibana
      template:
        src: templates/kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        owner: kibana
        group: kibana
        mode: 0644
      notify:
        - Restart Kibana

    - name: Set Kibana credentials in kibana.yml
      lineinfile:
        path: /etc/kibana/kibana.yml
        insertafter: EOF
        create: yes
        line: "{{ item }}"
      loop:
        - 'elasticsearch.username: "kibana_system"'
        - 'elasticsearch.password: "D7daU5h41C2rKd24"'

    - name: Enable and start Kibana service
      systemd:
        name: kibana
        enabled: yes
        state: started

    - name: Generate Kibana enrollment token
      command: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
      register: kibana_token

    - name: Display Kibana enrollment token
      debug:
        msg: "Kibana Enrollment Token: {{ kibana_token.stdout }}"

  handlers:
    - name: Restart Kibana
      systemd:
        name: kibana
        state: restarted
