---
- name: Install and configure Kibana in Docker
  hosts: kibana.internal-cloud
  become: yes
  tasks:
    - name: Check if containerd.io is installed
      shell: dpkg -l | grep containerd.io
      register: containerd_installed
      ignore_errors: true

    - name: Remove containerd.io if installed
      apt:
        name: containerd.io
        state: absent
      when: containerd_installed.rc == 0

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker if not already installed
      apt:
        name: docker.io
        state: present

    - name: Check if Elasticsearch image is already pulled
      command: docker images -q kibana:8.15.1
      register: kibana_image
      ignore_errors: true

    - name: Pull Elasticsearch image if not present
      command: docker pull kibana:8.15.1
      when: kibana_image.stdout == ""

    - name: Ensure Kibana config directory exists
      file:
        path: /opt/kibana/config
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Render Kibana configuration from template
      template:
        src: /HA-web/ansible-playbooks/templates/ELK/kibana.yml.j2
        dest: /opt/kibana/config/kibana.yml
        owner: root
        group: root
        mode: 0644

    - name: Run Kibana container
      community.docker.docker_container:
        name: kibana
        image: kibana:8.15.1
        state: started
        restart_policy: always
        ports:
          - "5601:5601"
        volumes:
          - /opt/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml