---
- name: Deploy nginx on Docker Swarm
  hosts: all
  become: yes
  tasks:
    - name: Pull nginx image
      command: docker pull nginx:latest

    - name: Check if nginx service exists
      command: docker service ls --filter name=nginx -q
      register: nginx_service_check
      failed_when: false
      changed_when: false
      when: "'docker_swarm_manager' in group_names"

    - name: Create nginx service in Docker Swarm
      command: docker service create --name nginx --replicas 1 --publish published=80,target=80 nginx:latest
      when: "'docker_swarm_manager' in group_names" and not nginx_service_check.stdout