---
- name: Deploy nginx on Docker Swarm
  hosts: docker_swarm_manager
  become: yes
  tasks:
    - name: Pull nginx image
      command: docker pull nginx:latest

    - name: Create nginx config
      docker_config:
        name: "nginx-index"
        data: "This is Nginx running on {{ ansible_default_ipv4.address }}"
        state: present
      delegate_to: "{{ item }}"
      loop: "{{ groups['all'] }}"

    - name: Copy nginx configuration
      docker_config:
        name: nginx-conf
        src: /home/user/nginx.conf
        state: present

    - name: Copy SSL certificate
      docker_secret:
        name: ssl-cert
        src: /home/user/cert.pem
        state: present

    - name: Copy SSL key
      docker_secret:
        name: ssl-key
        src: /home/user/key.pem
        state: present

    - name: Create nginx service in Docker Swarm
      command: >
        docker service create 
        --name nginx 
        --mode global 
        --publish published=80,target=80 
        --publish published=443,target=443
        --config src=nginx-index,target=/usr/share/nginx/html/index.html 
        --config src=nginx-conf,target=/etc/nginx/nginx.conf 
        --secret src=ssl-cert,target=/etc/ssl/certs/cert.pem 
        --secret src=ssl-key,target=/etc/ssl/private/key.pem 
        nginx:latest
