---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        update_cache: yes
        state: present
        
    - name: Initialize Docker Swarm
      hosts: first_machine_ip
      become: yes
      tasks:
        - name: Initialize Swarm
          command: docker swarm init --advertise-addr {{ ansible_host }}
          ignore_errors: yes
          register: swarm_result

        - name: Get Swarm join token for workers
          command: docker swarm join-token -q worker
          when: swarm_result is changed
          register: worker_token

        - name: Store worker token
          set_fact:
            swarm_worker_token: "{{ worker_token.stdout }}"

    - name: Join Swarm as worker
      hosts: second_machine_ip
      become: yes
      tasks:
        - name: Join Swarm cluster
          command: docker swarm join --token {{ hostvars['first_machine_ip']['swarm_worker_token'] }} {{ hostvars['first_machine_ip']['ansible_host'] }}:2377
          ignore_errors: yes
